<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No, Create New Account</name>
   <tag></tag>
   <elementGuidId>83f05b3d-331b-4711-8f41-2c323fd6c4eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='u_9_2_y2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_9_2_y2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d609376f-6fd7-4be4-b69b-2fbdb4cc51e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2242f99-0d01-4e3c-acb6-4e4cbab5b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 layerButton uiOverlayButton _4jy3 _517h _51sy</value>
      <webElementGuid>901e31b2-f6da-4512-ac01-f6978afb3390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f5f29165-3676-4617-a1c5-5afa8d250332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_9_2_y2</value>
      <webElementGuid>f9189a38-e594-4ab4-a516-6d7094fd0a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No, Create New Account</value>
      <webElementGuid>e0baa658-7180-452f-a814-2ae74766ab53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_9_2_y2&quot;)</value>
      <webElementGuid>b96aa276-148a-4763-b73a-13617b5f7854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_9_2_y2']</value>
      <webElementGuid>2a3004f2-13d7-4357-a12e-a9ff76d02c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='facebook']/body/div[5]/div[2]/div/div/div/div[3]/a</value>
      <webElementGuid>2099e261-d087-4ce3-af8f-7489ad237b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'No, Create New Account')]</value>
      <webElementGuid>c185b465-ebe6-41a2-87c2-09ac9ab85f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>d90f824c-6d5c-41d5-912e-78c94e65158a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/a</value>
      <webElementGuid>ec71f2ce-0b55-4125-933b-f3f1e414aabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_9_2_y2' and (text() = 'No, Create New Account' or . = 'No, Create New Account')]</value>
      <webElementGuid>a51810fc-3eab-4bd8-a701-55ee1856c098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
