<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up_1</name>
   <tag></tag>
   <elementGuidId>08597134-df63-40ec-9d9a-86bbb91dbcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_3_s_b1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'websubmit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_3_s_b1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7aedb57c-22f2-4dc2-a41f-4314fbb481c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f1130dc3-1da5-4587-992e-e217ff21a624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6j mvm _6wk _6wl _58mi _3ma _6o _6v</value>
      <webElementGuid>658955f9-14b7-4ca4-8542-b03d37d8a471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>websubmit</value>
      <webElementGuid>6a032266-4c71-4fe4-bdca-950387724188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_3_s_b1</value>
      <webElementGuid>abb2a30b-7694-47b4-a850-a13eb06af32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>38d2ca85-0484-4593-bf91-039b0238b721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_s_b1&quot;)</value>
      <webElementGuid>e8e7a9d6-b31b-4fa8-ac7a-436816829b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_3_s_b1']</value>
      <webElementGuid>476665af-74b3-49a8-b369-9e75b006a9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_form_box']/div[11]/button</value>
      <webElementGuid>dff18181-103e-4adf-b60b-4d5360f6a635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>ec7a4c9b-8c23-455c-8cf2-d6e513edcb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'websubmit' and @id = 'u_3_s_b1' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>abd64d97-5d34-4bd3-80d0-f970d6447d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
