<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reg_email___1</name>
   <tag></tag>
   <elementGuidId>246feca0-b86b-4d89-98f3-651906b95334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_3_g_wk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_3_g_wk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2a429d8-8329-4c4b-a60d-fdf72c961f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a40b1c85-b6dd-41a5-9dd4-82252d77b274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _58mg _5dba _2ph-</value>
      <webElementGuid>d490bdfe-810d-4439-838b-226453107c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f83fd218-08b9-41da-8090-b7c43fd6732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reg_email__</value>
      <webElementGuid>3ccd99c2-455f-4b15-812a-7467b77ef3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14dc549e-8502-4d93-8579-122266b8f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mobile number or email address</value>
      <webElementGuid>32d93228-ce36-4ad4-8b9f-6ecf49c5e8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_3_g_wk</value>
      <webElementGuid>e9d53891-4c06-48fd-b155-e015502458b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_g_wk&quot;)</value>
      <webElementGuid>009ecd0c-f644-4342-bd1e-a972a28c2729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_3_g_wk']</value>
      <webElementGuid>0856bb9f-4b09-4d35-8970-a6b7c1dcf727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_3_f_mz']/div/input</value>
      <webElementGuid>35ed8491-4c2d-47ab-b5de-5c28edcb479a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>7fd16a1e-c964-4a94-abf9-bc6a11745191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reg_email__' and @id = 'u_3_g_wk']</value>
      <webElementGuid>bb3d4fa0-ab86-4bd9-bdb7-8f15fbbdb271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
