<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Male</name>
   <tag></tag>
   <elementGuidId>051b025e-780f-4cbf-b297-b2c256f3684c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Male' or . = 'Male')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='u_3_o_RO']/span[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9daa4381-bc00-4952-8ee8-7e3ee7bcfd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_58mt</value>
      <webElementGuid>ce251c3b-0268-4b45-aeca-042537b9d96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>u_3_5_9K</value>
      <webElementGuid>2d578017-593f-4b78-ba77-a977dde064e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>2590b3b4-dab1-442e-aa8d-67e40375eddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_o_RO&quot;)/span[@class=&quot;_5k_2 _5dba&quot;]/label[@class=&quot;_58mt&quot;]</value>
      <webElementGuid>fd0bb790-fc57-41bb-8dfc-a8186aba8577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_3_o_RO']/span[2]/label</value>
      <webElementGuid>070c8c36-c337-40b2-b767-48c5cff2003b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/label</value>
      <webElementGuid>226383be-cace-4be2-9fdb-3f722c40edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>2b912a3e-0a0b-4165-9dd6-a38a6d721ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
