<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK</name>
   <tag></tag>
   <elementGuidId>792e3d8d-21f1-42fb-84af-71a016b2fab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._42ft._42fu.layerCancel.uiOverlayButton.selected._42g-._42gy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='goURI(&quot;\/&quot;, true);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48c9eccb-c166-4ade-9168-7e4c3cc4c0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6580d9a3-91e3-4ce9-a0c1-b383e83afc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _42fu layerCancel uiOverlayButton selected _42g- _42gy</value>
      <webElementGuid>6ffa60fc-d0f4-46d5-9e1d-1d0f08080857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>860f816b-a267-440f-9632-815ed582f550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>goURI(&quot;\/&quot;, true);</value>
      <webElementGuid>f350c113-98d1-41f6-a9f4-89fc13496084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ae924b7-9900-4bd0-a9af-40e37bf6579b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>5aa64740-a1e1-42f4-b10e-9ebb46273b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facebook&quot;)/body[@class=&quot;_4-u5 _8n26 _9l2i fbx hideBanner _-kb _605a m_2l9ovsfet chrome webkit x1 Locale_en_GB cores-gte4 _19_u&quot;]/div[@class=&quot;_10 uiLayer _4-hy _3qw&quot;]/div[@class=&quot;_1yv&quot;]/div[@class=&quot;_t _9l18&quot;]/div[1]/div[1]/div[@class=&quot;_14&quot;]/div[@class=&quot;pam uiOverlayFooter uiBoxGray topborder&quot;]/a[@class=&quot;_42ft _42fu layerCancel uiOverlayButton selected _42g- _42gy&quot;]</value>
      <webElementGuid>580a7224-a106-401a-b2fb-610e91abd959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='goURI(&quot;\/&quot;, true);']</value>
      <webElementGuid>81f5cccb-3e3b-4996-ac04-493092fb4c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='facebook']/body/div[5]/div[2]/div/div/div/div[3]/div/a</value>
      <webElementGuid>b20eaa4c-1a96-41b2-bd9b-7a19ac0507ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OK')]</value>
      <webElementGuid>23379cac-7b12-460f-ab46-9686b3f3107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>6c31d102-ce3c-46a3-b913-6e04851200f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>021f7837-45f4-4970-b547-9523445e3c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>21d064b8-2b49-4ec3-a49a-42ba27e6fbe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
